# Generated by Django 3.2.12 on 2022-02-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zip', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=250)),
                ('web', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-first_name'],
            },
        ),
    ]
